{{ if .Values.mysql.enabled }}
# Source: mysql/templates/primary/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hummerrisk-mysql-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: mysql
data:
  my.cnf: |-
    [mysqld]
    datadir=/var/lib/mysql

    default-storage-engine=INNODB
    character_set_server=utf8
    lower_case_table_names=1
    table_open_cache=128
    max_connections=2000
    max_connect_errors=6000
    innodb_file_per_table=1
    innodb_buffer_pool_size=1G
    max_allowed_packet=1G
    slave_max_allowed_packet=1G
    transaction_isolation=READ-COMMITTED
    innodb_flush_method=O_DIRECT
    innodb_lock_wait_timeout=1800
    innodb_flush_log_at_trx_commit=0
    sync_binlog=0
    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    skip-name-resolve

    [mysql]
    default-character-set=utf8

    [client]
    port=3306
    socket=/var/run/mysqld/mysqld.sock
    default-character-set=UTF8

    [mysql.server]
    default-character-set=utf8
{{ end }}